{{- if .Values.auth.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: cooperage-gateway-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cooperage
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc }}
{{- end }}
