apiVersion: v1
kind: ServiceAccount
metadata:
  name: cooperage-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cooperage
    app.kubernetes.io/instance: {{ .Release.Name }}
