"""
Cooperage Example: PDF Report Generator

Compiles workspace files (text, JSON, images, CSV) into a formatted PDF
report. Pairs well with csv-analyzer and web-scraper — analyze data,
then generate a polished report.

Tools:
  generate_report — compile workspace files into a PDF
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path

import uvicorn
from mcp.server.fastmcp import FastMCP
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

WORKSPACE = Path(os.environ.get("COOPERAGE_WORKSPACE", "/workspace"))
WORKSPACE.mkdir(parents=True, exist_ok=True)

mcp = FastMCP("pdf-report", json_response=True, stateless_http=True)


def _safe_path(filename: str) -> Path:
    resolved = (WORKSPACE / filename).resolve()
    if not str(resolved).startswith(str(WORKSPACE.resolve())):
        raise ValueError(f"Path {filename!r} escapes workspace")
    return resolved


@mcp.tool()
def generate_report(
    title: str,
    sections: list[dict],
    output: str = "report.pdf",
    author: str = "Cooperage",
) -> str:
    """Generate a PDF report from workspace content.

    Each section is a dict with:
      - heading: str — section title
      - text: str (optional) — paragraph text
      - file: str (optional) — path to a workspace file to include
        (.png/.jpg → embedded image, .csv → table, .json → formatted JSON, .txt → text block)

    Example:
      generate_report(
        title="Analysis Report",
        sections=[
          {"heading": "Summary", "text": "This report covers..."},
          {"heading": "Data", "file": "results.csv"},
          {"heading": "Chart", "file": "chart.png"},
        ],
        output="report.pdf"
      )
    """
    out_path = _safe_path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(str(out_path), pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title page
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=28, spaceAfter=30,
    )
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(
        f"Generated by {author} — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Normal"],
    ))
    story.append(PageBreak())

    # Sections
    for section in sections:
        heading = section.get("heading", "Untitled")
        story.append(Paragraph(heading, styles["Heading1"]))
        story.append(Spacer(1, 12))

        if "text" in section:
            story.append(Paragraph(section["text"], styles["Normal"]))
            story.append(Spacer(1, 12))

        if "file" in section:
            file_path = _safe_path(section["file"])
            if not file_path.exists():
                story.append(Paragraph(
                    f"[File not found: {section['file']}]",
                    ParagraphStyle("Error", parent=styles["Normal"], textColor=colors.red),
                ))
            else:
                ext = file_path.suffix.lower()
                if ext in (".png", ".jpg", ".jpeg", ".gif"):
                    img = Image(str(file_path), width=5 * inch, height=3.5 * inch)
                    img.hAlign = "CENTER"
                    story.append(img)
                elif ext == ".csv":
                    _add_csv_table(story, file_path, styles)
                elif ext == ".json":
                    data = json.loads(file_path.read_text())
                    formatted = json.dumps(data, indent=2)
                    if len(formatted) > 3000:
                        formatted = formatted[:3000] + "\n..."
                    story.append(Paragraph(
                        f"<pre>{formatted}</pre>",
                        ParagraphStyle("Code", parent=styles["Code"], fontSize=8),
                    ))
                else:
                    text = file_path.read_text()[:2000]
                    story.append(Paragraph(text, styles["Normal"]))

            story.append(Spacer(1, 12))

    doc.build(story)
    return json.dumps({"report": output, "sections": len(sections), "pages": "generated"})


def _add_csv_table(story, file_path: Path, styles):
    """Add a CSV file as a formatted table to the PDF."""
    import csv
    with open(file_path) as f:
        reader = csv.reader(f)
        rows = list(reader)

    if not rows:
        story.append(Paragraph("[Empty CSV]", styles["Normal"]))
        return

    # Limit to 50 rows for readability
    header = rows[0]
    data_rows = rows[1:51]
    if len(rows) > 51:
        data_rows.append(["..." for _ in header])

    table_data = [header] + data_rows
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
    ]))
    story.append(table)


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8000"))
    uvicorn.run(mcp.streamable_http_app(), host="0.0.0.0", port=port)
